---
title: "Simulation result - revision"
output: html_notebook
author : Wookyeong Song
date : 15th, March, 2020
---

```{r}
Sys.setlocale('LC_ALL','C')
library(fdapace)
library(fda)
library(cluster)
library(factoextra)
library(fields)
library(lubridate)
library(funFEM)
library(funHDDC)
library(mclust)
library(combinat)

load("C:\\Users\\user\\Desktop\\WK\\class\\intern\\hsoh\\step_79.RData")
source('C:\\Users\\user\\Desktop\\WK\\class\\intern\\hsoh\\2003\\function_newnormal.R')
```



## Simulation Set - Amount


```{r,include=FALSE}
true = c(rep(1,100),rep(2,100),rep(3,100))

ccr <- function(result, true) {
  if(length(result) != length(true)) {warning('result vector and true vector has different size')}
  return(sum(true == result)/length(result))
}


ccr_kmeans_amount=vector()
rand_kmeans_amount=vector()

ccr_pam_amount=vector()
rand_pam_amount=vector()

ccr_funfem_amount=vector()
rand_funfem_amount=vector()

ccr_funhddc_amount=vector()
rand_funhddc_amount=vector()

for (k in 1:100) {
  set.seed(k)
  x_low <- as.integer(rnorm(100,150,15))
  x_mid <- as.integer(rnorm(100,250,15))
  x_high <- as.integer(rnorm(100,350,15))
  
  sample_low_afternoon <- matrix(0,nrow=1440,ncol = 100)
  inten_prop_afternoon = c(0,0.02,0.04,0.08,0.15,0.25,0.25,0.1,0.06,0.03,0.02,0)
  tmp1 = inten_prop_afternoon[c(1:2,11:12)]
  tmp2 = inten_prop_afternoon[5:8]
  tmp3 = inten_prop_afternoon[c(3:4,9:10)]
  
  for (i in 1:100) {
    tmp1 <- tmp1[sample(4,4,replace=FALSE)]
    tmp2 <- tmp2[sample(4,4,replace=FALSE)]
    tmp3 <- tmp3[sample(4,4,replace=FALSE)]
    inten_prop_afternoon <- c(tmp1[1:2],tmp3[1:2],tmp2,tmp3[3:4],tmp1[3:4])
    for (j in 1:12) {
      walk_location = sample((120*j-119):(120*j),as.integer(x_low[i]*inten_prop_afternoon[j]),replace = FALSE)
      sample_low_afternoon[walk_location,i] <-as.integer(rexp(as.integer(x_low[i]*inten_prop_afternoon[j]),1/32.5))
    }
  }
  
  sample_mid_afternoon <- matrix(0,nrow=1440,ncol = 100)
  inten_prop_afternoon = c(0,0.02,0.04,0.08,0.15,0.25,0.25,0.1,0.06,0.03,0.02,0)
  tmp1 = inten_prop_afternoon[c(1:2,11:12)]
  tmp2 = inten_prop_afternoon[5:8]
  tmp3 = inten_prop_afternoon[c(3:4,9:10)]
  for (i in 1:100) {
    tmp1 <- tmp1[sample(4,4,replace=FALSE)]
    tmp2 <- tmp2[sample(4,4,replace=FALSE)]
    tmp3 <- tmp3[sample(4,4,replace=FALSE)]
    inten_prop_afternoon <- c(tmp1[1:2],tmp3[1:2],tmp2,tmp3[3:4],tmp1[3:4])
    for (j in 1:12) {
      walk_location = sample((120*j-119):(120*j),as.integer(x_mid[i]*inten_prop_afternoon[j]),replace = FALSE)
      sample_mid_afternoon[walk_location,i] <-as.integer(rexp(as.integer(x_mid[i]*inten_prop_afternoon[j]),1/32.5))
    }
  }
  
  sample_high_afternoon <- matrix(0,nrow=1440,ncol = 100)
  inten_prop_afternoon = c(0,0.02,0.04,0.08,0.15,0.25,0.25,0.1,0.06,0.03,0.02,0)
  tmp1 = inten_prop_afternoon[c(1:2,11:12)]
  tmp2 = inten_prop_afternoon[5:8]
  tmp3 = inten_prop_afternoon[c(3:4,9:10)]
  for (i in 1:100) {
    tmp1 <- tmp1[sample(4,4,replace=FALSE)]
    tmp2 <- tmp2[sample(4,4,replace=FALSE)]
    tmp3 <- tmp3[sample(4,4,replace=FALSE)]
    inten_prop_afternoon <- c(tmp1[1:2],tmp3[1:2],tmp2,tmp3[3:4],tmp1[3:4])
    for (j in 1:12) {
      walk_location = sample((120*j-119):(120*j),as.integer(x_high[i]*inten_prop_afternoon[j]),replace = FALSE)
      sample_high_afternoon[walk_location,i] <-as.integer(rexp(as.integer(x_high[i]*inten_prop_afternoon[j]),1/32.5))
    }
  }
  
  simulation_step = cbind(sample_low_afternoon,sample_mid_afternoon,sample_high_afternoon)
  
  sim_data_amount <- convert_amount(simulation_step)
  sim_data_intensity <- convert_intensity(simulation_step,8)
  sim_data_pattern <- convert_pattern(simulation_step,3)
  
  ###############################################MFPCA####################################################
  sim_data_array = array(data=NA,dim=c(1440,ncol(simulation_step),3))
  sim_data_array[,,1]<-sim_data_amount
  sim_data_array[,,2]<-sim_data_intensity
  sim_data_array[,,3]<-sim_data_pattern
  
  fdabasis = create.bspline.basis(rangeval=c(0,1440),norder=4,breaks = seq(0,1440,by=6))
  fdatime = seq(1, 1440, by=1)
  sim_fdafd = smooth.basis(fdatime, sim_data_array, fdabasis)$fd
  
  stepPca = pca.fd(sim_fdafd,nharm=10)
  a<-vector()
  for(q in 1:10){
  	a[q]=sum(stepPca$varprop[1:q])
  	}
  q=which(a>0.9)[1]
  funPCscore<-stepPca$scores[,1:q,1]+stepPca$scores[,1:q ,2]+stepPca$scores[, 1:q,3]
  
  ##Kmeans
  num_cl=3
  MCluster <- kmeans(funPCscore, centers= num_cl, iter.max = 100000)
  
  cluster_result = best_match_factor(true,MCluster$cluster)
  
  ccr_kmeans_amount[k] <- ccr(true,cluster_result)
  rand_kmeans_amount[k] <- adjustedRandIndex(true,cluster_result)
  
  ##PAM
  num_cl=3
  MCluster <- pam(funPCscore, num_cl, metric="manhattan")
  
  cluster_result = best_match_factor(true,MCluster$cluster)
  
  ccr_pam_amount[k] <- ccr(true,cluster_result)
  rand_pam_amount[k] <- adjustedRandIndex(true,cluster_result)
  
  ## FunFEM
  fdabasis = create.bspline.basis(rangeval=c(0,1440),norder=4,nbasis=21)
  fdatime = seq(1, 1440, by=1)
  sim_fdafd = smooth.basis(fdatime, simulation_step, fdabasis)$fd

  res <- funFEM(sim_fdafd,K=3)
  cluster_result = best_match_factor(true,res$cls)
  
  ccr_funfem_amount[k] <- ccr(true,cluster_result)
  rand_funfem_amount[k] <- adjustedRandIndex(true,cluster_result)
  
  ##FunHDDC
  fdabasis = create.fourier.basis(rangeval=c(0,1440),period = 1440,nbasis=21)
  fdatime = seq(1, 1440, by=1)
  sim_fdafd = smooth.basis(fdatime, simulation_step, fdabasis)$fd

  res <- funHDDC(sim_fdafd,K=3)
  cluster_result = best_match_factor(true,res$class)
  
  ccr_funhddc_amount[k] <- ccr(true,cluster_result)
  rand_funhddc_amount[k] <- adjustedRandIndex(true,cluster_result)
  
}

```


```{r}
##CCR
mean(ccr_kmeans_amount)
sd(ccr_kmeans_amount)

mean(ccr_pam_amount)
sd(ccr_pam_amount)

mean(ccr_funfem_amount)
sd(ccr_funfem_amount)

mean(ccr_funhddc_amount)
sd(ccr_funhddc_amount)

##AdjustedRandindex
mean(rand_kmeans_amount)
sd(rand_kmeans_amount)

mean(rand_pam_amount)
sd(rand_pam_amount)

mean(rand_funfem_amount)
sd(rand_funfem_amount)

mean(rand_funhddc_amount)
sd(rand_funhddc_amount)
```


## Simulation Set - Intensity


```{r,include=FALSE}
true = c(rep(1,100),rep(2,100),rep(3,100))

ccr <- function(result, true) {
  if(length(result) != length(true)) {warning('result vector and true vector has different size')}
  return(sum(true == result)/length(result))
}


ccr_kmeans_intensity=vector()
rand_kmeans_intensity=vector()

ccr_pam_intensity=vector()
rand_pam_intensity=vector()

ccr_funfem_intensity=vector()
rand_funfem_intensity=vector()

ccr_funhddc_intensity=vector()
rand_funhddc_intensity=vector()

for (k in 1:100) {
  set.seed(k)
  x_intensity <- as.integer(rnorm(300,150,10))

  sample_low_evening <- matrix(0,nrow=1440,ncol = 100)
  inten_low_evening = sort(c(0.05,0.05,0.05,0.05,0.075,0.075,0.075,0.075,0.125,0.125,0.125,0.125))
  tmp1 = inten_low_evening[1:4]
  tmp2 = inten_low_evening[5:8]
  tmp3 = inten_low_evening[9:12]
  
  for (i in 1:100) {
    tmp1 <- tmp1[sample(4,4,replace=FALSE)]
    tmp2 <- tmp2[sample(4,4,replace=FALSE)]
    tmp3 <- tmp3[sample(4,4,replace=FALSE)]
    inten_low_evening <- c(tmp1,tmp2,tmp3)
    for (j in 1:12) {
      walk_location = sample((120*j-119):(120*j),as.integer(x_intensity[i]*inten_low_evening[j]),replace = FALSE)
      sample_low_evening[walk_location,i] <-as.integer(rexp(as.integer(x_intensity[i]*inten_low_evening[j]),1/20))
    }
  }
  
  sample_mid_evening <- matrix(0,nrow=1440,ncol = 100)
  inten_mid_evening = c(0,0.1,0.1,0.0,0.15,0.15,0.0,0.0,0.0,0.0,0.25,0.25)
  tmp1 = inten_mid_evening[1:4]
  tmp2 = inten_mid_evening[5:8]
  tmp3 = inten_mid_evening[9:12]
  for (i in 1:100) {
    tmp1 <- tmp1[sample(4,4,replace=FALSE)]
    tmp2 <- tmp2[sample(4,4,replace=FALSE)]
    tmp3 <- tmp3[sample(4,4,replace=FALSE)]
    inten_mid_evening <- c(tmp1,tmp2,tmp3)
    for (j in 1:12) {
      walk_location = sample((120*j-119):(120*j),as.integer(x_intensity[100+i]*inten_mid_evening[j]),replace = FALSE)
      sample_mid_evening[walk_location,i] <-as.integer(rexp(as.integer(x_intensity[100+i]*inten_mid_evening[j]),1/20))
    }
  }
  
  sample_high_evening <- matrix(0,nrow=1440,ncol = 100)
  inten_high_evening = c(0,0.0,0.2,0.0,0.0,0.0,0.3,0.0,0.0,0.0,0.0,0.5)
  tmp1 = inten_high_evening[1:4]
  tmp2 = inten_high_evening[5:8]
  tmp3 = inten_high_evening[9:12]
  for (i in 1:100) {
    tmp1 <- tmp1[sample(4,4,replace=FALSE)]
    tmp2 <- tmp2[sample(4,4,replace=FALSE)]
    tmp3 <- tmp3[sample(4,4,replace=FALSE)]
    inten_high_evening <- c(tmp1,tmp2,tmp3)
    for (j in 1:12) {
      walk_location = sample((120*j-119):(120*j),as.integer(x_intensity[200+i]*inten_high_evening[j]),replace = FALSE)
      sample_high_evening[walk_location,i] <-as.integer(rexp(as.integer(x_intensity[200+i]*inten_high_evening[j]),1/20))
    }
  }
  
  simulation_step = cbind(sample_low_evening,sample_mid_evening,sample_high_evening)
  
  sim_data_amount <- convert_amount(simulation_step)
  sim_data_intensity <- convert_intensity(simulation_step,8)
  sim_data_pattern <- convert_pattern(simulation_step,3)
  
  ###############################################MFPCA####################################################
  sim_data_array = array(data=NA,dim=c(1440,ncol(simulation_step),3))
  sim_data_array[,,1]<-sim_data_amount
  sim_data_array[,,2]<-sim_data_intensity
  sim_data_array[,,3]<-sim_data_pattern
  
  fdabasis = create.bspline.basis(rangeval=c(0,1440),norder=4,breaks = seq(0,1440,by=6))
  fdatime = seq(1, 1440, by=1)
  sim_fdafd = smooth.basis(fdatime, sim_data_array, fdabasis)$fd
  
  stepPca = pca.fd(sim_fdafd,nharm=10)
  a<-vector()
  for(q in 1:10){
  	a[q]=sum(stepPca$varprop[1:q])
  	}
  q=which(a>0.9)[1]
  funPCscore<-stepPca$scores[,1:q,1]+stepPca$scores[,1:q ,2]+stepPca$scores[, 1:q,3]
  
  ##Kmeans
  num_cl=3
  MCluster <- kmeans(funPCscore, centers= num_cl, iter.max = 100000)
  cluster_result = best_match_factor(true,MCluster$cluster)
  
  ccr_kmeans_intensity[k] <- ccr(true,cluster_result)
  rand_kmeans_intensity[k] <- adjustedRandIndex(true,cluster_result)
  
  ##PAM
  num_cl=3
  MCluster <- pam(funPCscore, num_cl, metric="manhattan")
  cluster_result = best_match_factor(true,MCluster$cluster)
  
  ccr_pam_intensity[k] <- ccr(true,cluster_result)
  rand_pam_intensity[k] <- adjustedRandIndex(true,cluster_result)
  
  ## FunFEM
  fdabasis = create.bspline.basis(rangeval=c(0,1440),norder=4,nbasis=21)
  fdatime = seq(1, 1440, by=1)
  sim_fdafd = smooth.basis(fdatime, simulation_step, fdabasis)$fd

  res <- funFEM(sim_fdafd,K=3)
  cluster_result = best_match_factor(true,res$cls)
  
  ccr_funfem_intensity[k] <- ccr(true,cluster_result)
  rand_funfem_intensity[k] <- adjustedRandIndex(true,cluster_result)
  
  ##FunHDDC
  fdabasis = create.fourier.basis(rangeval=c(0,1440),period = 1440,nbasis=21)
  fdatime = seq(1, 1440, by=1)
  sim_fdafd = smooth.basis(fdatime, simulation_step, fdabasis)$fd

  res <- funHDDC(sim_fdafd,K=3)
  cluster_result = best_match_factor(true,res$class)
  
  ccr_funhddc_intensity[k] <- ccr(true,cluster_result)
  rand_funhddc_intensity[k] <- adjustedRandIndex(true,cluster_result)
  
}


```

Intensity sort 할 때 

```{r}
##CCR 2,3,5
mean(ccr_kmeans_intensity)
sd(ccr_kmeans_intensity)

mean(ccr_pam_intensity)
sd(ccr_pam_intensity)

mean(ccr_funfem_intensity)
sd(ccr_funfem_intensity)

mean(ccr_funhddc_intensity)
sd(ccr_funhddc_intensity)

##AdjustedRandindex
mean(rand_kmeans_intensity)
sd(rand_kmeans_intensity)

mean(rand_pam_intensity)
sd(rand_pam_intensity)

mean(rand_funfem_intensity)
sd(rand_funfem_intensity)

mean(rand_funhddc_intensity)
sd(rand_funhddc_intensity)
```




## Simulation Set - Pattern

```{r}
true = c(rep(1,100),rep(2,100),rep(3,100))

ccr <- function(result, true) {
  if(length(result) != length(true)) {warning('result vector and true vector has different size')}
  return(sum(true == result)/length(result))
}



ccr_kmeans_pattern=vector()
rand_kmeans_pattern=vector()

ccr_pam_pattern=vector()
rand_pam_pattern=vector()

ccr_funfem_pattern=vector()
rand_funfem_pattern=vector()

ccr_funhddc_pattern=vector()
rand_funhddc_pattern=vector()

for (k in 1:100) {
  set.seed(k)
  x_pattern <- as.integer(rnorm(300,250,15))
  sample_mid_morning <- matrix(0,nrow=1440,ncol = 100)
  inten_prop_morning = c(0.12,0.13,0.1,0.1,0.1,0.1,0.07,0.08,0.05,0.05,0.05,0.05)
  tmp1 = inten_prop_morning[1:4]
  tmp2 = inten_prop_morning[5:8]
  tmp3 = inten_prop_morning[9:12]
  for (i in 1:100) {
    tmp1 <- tmp1[sample(4,4,replace=FALSE)]
    tmp2 <- tmp2[sample(4,4,replace=FALSE)]
    tmp3 <- tmp3[sample(4,4,replace=FALSE)]
    inten_prop_morning <- c(tmp1,tmp2,tmp3)
    for (j in 1:12) {
      walk_location = sample((120*j-119):(120*j),as.integer(x_pattern[i]*inten_prop_morning[j]),replace = FALSE)
      sample_mid_morning[walk_location,i] <-as.integer(rexp(as.integer(x_pattern[i]*inten_prop_morning[j]),1/32.5))
    }
  }
  
  
  
  sample_mid_afternoon <- matrix(0,nrow=1440,ncol = 100)
  inten_prop_afternoon = c(0.05,0.05,0.08,0.1,0.1,0.13,0.12,0.1,0.1,0.07,0.05,0.05)
  
  tmp1 = inten_prop_afternoon[c(1:2,11:12)]
  tmp2 = inten_prop_afternoon[5:8]
  tmp3 = inten_prop_afternoon[c(3:4,9:10)]
  for (i in 1:100) {
    tmp1 <- tmp1[sample(4,4,replace=FALSE)]
    tmp2 <- tmp2[sample(4,4,replace=FALSE)]
    tmp3 <- tmp3[sample(4,4,replace=FALSE)]
    inten_prop_afternoon <- c(tmp1[1:2],tmp3[1:2],tmp2,tmp3[3:4],tmp1[3:4])
    for (j in 1:12) {
      walk_location = sample((120*j-119):(120*j),as.integer(x_pattern[100+i]*inten_prop_afternoon[j]),replace = FALSE)
      sample_mid_afternoon[walk_location,i] <-as.integer(rexp(as.integer(x_pattern[100+i]*inten_prop_afternoon[j]),1/32.5))
    }
  }
  
  
  
  
  sample_mid_evening <- matrix(0,nrow=1440,ncol = 100)
  inten_prop_evening = sort(inten_prop_morning)
  tmp1 = inten_prop_evening[1:4]
  tmp2 = inten_prop_evening[5:8]
  tmp3 = inten_prop_evening[9:12]
  for (i in 1:100) {
    tmp1 <- tmp1[sample(4,4,replace=FALSE)]
    tmp2 <- tmp2[sample(4,4,replace=FALSE)]
    tmp3 <- tmp3[sample(4,4,replace=FALSE)]
    inten_prop_evening <- c(tmp1,tmp2,tmp3) 
    for (j in 1:12) {
      walk_location = sample((120*j-119):(120*j),as.integer(x_pattern[200+i]*inten_prop_evening[j]),replace = FALSE)
      sample_mid_evening[walk_location,i] <-as.integer(rexp(as.integer(x_pattern[200+i]*inten_prop_evening[j]),1/32.5))
    }
  }
  simulation_step = cbind(sample_low_evening,sample_mid_evening,sample_high_evening)
  
  sim_data_amount <- convert_amount(simulation_step)
  sim_data_intensity <- convert_intensity(simulation_step,8)
  sim_data_pattern <- convert_pattern(simulation_step,3)
  
  ###############################################MFPCA####################################################
  sim_data_array = array(data=NA,dim=c(1440,ncol(simulation_step),3))
  sim_data_array[,,1]<-sim_data_amount
  sim_data_array[,,2]<-sim_data_intensity
  sim_data_array[,,3]<-sim_data_pattern
  
  fdabasis = create.bspline.basis(rangeval=c(0,1440),norder=4,breaks = seq(0,1440,by=6))
  fdatime = seq(1, 1440, by=1)
  sim_fdafd = smooth.basis(fdatime, sim_data_array, fdabasis)$fd
  
  stepPca = pca.fd(sim_fdafd,nharm=10)
  a<-vector()
  for(q in 1:10){
  	a[q]=sum(stepPca$varprop[1:q])
  	}
  q=which(a>0.9)[1]
  funPCscore<-stepPca$scores[,1:q,1]+stepPca$scores[,1:q ,2]+stepPca$scores[, 1:q,3]
  
  ##Kmeans
  num_cl=3
  MCluster <- kmeans(funPCscore, centers= num_cl, iter.max = 100000)
  cluster_result = best_match_factor(true,MCluster$cluster)
  
  ccr_kmeans_pattern[k] <- ccr(true,cluster_result)
  rand_kmeans_pattern[k] <- adjustedRandIndex(true,cluster_result)
  
  ##PAM
  num_cl=3
  MCluster <- pam(funPCscore, num_cl, metric="manhattan")
  cluster_result = best_match_factor(true,MCluster$cluster)
  
  ccr_pam_pattern[k] <- ccr(true,cluster_result)
  rand_pam_pattern[k] <- adjustedRandIndex(true,cluster_result)
  
  ## FunFEM
  fdabasis = create.bspline.basis(rangeval=c(0,1440),norder=4,nbasis=21)
  fdatime = seq(1, 1440, by=1)
  sim_fdafd = smooth.basis(fdatime, simulation_step, fdabasis)$fd

  res <- funFEM(sim_fdafd,K=3)
  cluster_result = best_match_factor(true,res$cls)
  
  ccr_funfem_pattern[k] <- ccr(true,cluster_result)
  rand_funfem_pattern[k] <- adjustedRandIndex(true,cluster_result)
  
  ##FunHDDC
  fdabasis = create.fourier.basis(rangeval=c(0,1440),period = 1440,nbasis=21)
  fdatime = seq(1, 1440, by=1)
  sim_fdafd = smooth.basis(fdatime, simulation_step, fdabasis)$fd

  res <- funHDDC(sim_fdafd,K=3)
  
  cluster_result = best_match_factor(true,res$class)
  
  ccr_funhddc_pattern[k] <- ccr(true,cluster_result)
  rand_funhddc_pattern[k] <- adjustedRandIndex(true,cluster_result)
  
}

```


```{r}
##CCR
mean(ccr_kmeans_pattern)
sd(ccr_kmeans_pattern)

mean(ccr_pam_pattern)
sd(ccr_pam_pattern)

mean(ccr_funfem_pattern)
sd(ccr_funfem_pattern)

mean(ccr_funhddc_pattern)
sd(ccr_funhddc_pattern)

##AdjustedRandindex
mean(rand_kmeans_pattern)
sd(rand_kmeans_pattern)

mean(rand_pam_pattern)
sd(rand_pam_pattern)

mean(rand_funfem_pattern)
sd(rand_funfem_pattern)

mean(rand_funhddc_pattern)
sd(rand_funhddc_pattern)
```



## Simulation Set - doppler shift

```{r,include=FALSE}
true = c(rep(1,50),rep(2,50),rep(3,50),rep(4,50))

ccr <- function(result, true) {
  if(length(result) != length(true)) {warning('result vector and true vector has different size')}
  return(sum(true == result)/length(result))
}


ccr_kmeans_dopshif=vector()
rand_kmeans_dopshif=vector()

ccr_pam_dopshif=vector()
rand_pam_dopshif=vector()

ccr_funfem_dopshif=vector()
rand_funfem_dopshif=vector()

ccr_funhddc_dopshif=vector()
rand_funhddc_dopshif=vector()

for (k in 1:100) {
  set.seed(k)
  time = seq(0,511/512,length.out=512)
  
  doppler1 = matrix(0,nrow=512,ncol=50)
  
  doppler1[1,] = rnorm(50,0.6,0.05)
  for (i in 2:512) {
    doppler1[i,]=rnorm(50,0.6+0.6*sqrt(time[i]*(1-time[i]))*sin(2.1*pi/(time[i])),0.05)
  }
  
  
  doppler2 = matrix(0,nrow=512,ncol=50)
  for (i in 1:512) {
    doppler2[i,]=rnorm(50,0.6+0.6*sqrt(time[i]*(1-time[i]))*sin(2.1*pi/(time[i]-1/3)),0.05)
  }
  
  
  doppler3 = matrix(0,nrow=512,ncol=50)
  for (i in 1:512) {
    doppler3[i,]=rnorm(50,0.6+0.6*sqrt(time[i]*(1-time[i]))*sin(2.1*pi/(time[i]-2/3)),0.05)
  }
  
  
  doppler4 = matrix(0,nrow=512,ncol=50)
  for (i in 1:512) {
    doppler4[i,]=rnorm(50,0.6+0.6*sqrt(time[i]*(1-time[i]))*sin(2.1*pi/(time[i]-1)),0.05)
  }
  
  doppler = cbind(doppler1,doppler2,doppler3,doppler4)

    
  sim_doppler_amount <- convert_amount(doppler)
  sim_doppler_intensity <- convert_intensity(doppler,8)
  sim_doppler_pattern <- convert_pattern(doppler,4)
  
  
  ###############################################MFPCA####################################################
  sim_doppler_array = array(data=NA,dim=c(512,ncol(doppler),3))
  sim_doppler_array[,,1]<-sim_doppler_amount
  sim_doppler_array[,,2]<-sim_doppler_intensity
  sim_doppler_array[,,3]<-sim_doppler_pattern
  
  fdabasis = create.bspline.basis(rangeval=c(0,512),norder=4,breaks = seq(0,512,by=2))
  fdatime = seq(1, 512, by=1)
  sim_doppler_fdafd = smooth.basis(fdatime, sim_doppler_array, fdabasis)$fd
  
  dopplerPca = pca.fd(sim_doppler_fdafd,nharm=10)
  a<-vector()
  for(q in 1:10){
  	a[q]=sum(dopplerPca$varprop[1:q])
  	}
  q=which(a>0.9)[1]
  funPCscore<-dopplerPca$scores[,1:q,1]+dopplerPca$scores[,1:q ,2]+dopplerPca$scores[, 1:q,3]

  ##Kmeans
  num_cl=4
  MCluster <- kmeans(funPCscore, centers= num_cl, iter.max = 100000)
  cluster_result = best_match_factor(true,MCluster$cluster)
  
  ccr_kmeans_dopshif[k] <- ccr(true,cluster_result)
  rand_kmeans_dopshif[k] <- adjustedRandIndex(true,cluster_result)
  
  ##PAM
  num_cl=4
  MCluster <- pam(funPCscore, num_cl, metric="manhattan")
  cluster_result = best_match_factor(true,MCluster$cluster)
  
  ccr_pam_dopshif[k] <- ccr(true,cluster_result)
  rand_pam_dopshif[k] <- adjustedRandIndex(true,cluster_result)
  
  ## FunFEM
  fdabasis = create.bspline.basis(rangeval=c(0,512),norder=4,nbasis=21)
  fdatime = seq(1, 512, by=1)
  sim_doppler_fdafd = smooth.basis(fdatime, doppler, fdabasis)$fd
  res = funFEM(sim_doppler_fdafd,K=4)

  cluster_result = best_match_factor(true,res$cls)
  
  ccr_funfem_dopshif[k] <- ccr(true,cluster_result)
  rand_funfem_dopshif[k] <- adjustedRandIndex(true,cluster_result)
  
  ##FunHDDC
  fdabasis = create.fourier.basis(rangeval=c(0,512),period = 512)
  fdatime = seq(1, 512, by=1)
  sim_doppler_fdafd = smooth.basis(fdatime, doppler, fdabasis)$fd

  res <- funHDDC(sim_doppler_fdafd,K=4)
  
  cluster_result = best_match_factor(true,res$class)
  
  ccr_funhddc_dopshif[k] <- ccr(true,cluster_result)
  rand_funhddc_dopshif[k] <- adjustedRandIndex(true,cluster_result)
  
}
```


```{r}
##CCR
mean(ccr_kmeans_dopshif)
sd(ccr_kmeans_dopshif)

mean(ccr_pam_dopshif)
sd(ccr_pam_dopshif)

mean(ccr_funfem_dopshif)
sd(ccr_funfem_dopshif)

mean(ccr_funhddc_dopshif)
sd(ccr_funhddc_dopshif)

##AdjustedRandindex
mean(rand_kmeans_dopshif)
sd(rand_kmeans_dopshif)

mean(rand_pam_dopshif)
sd(rand_pam_dopshif)

mean(rand_funfem_dopshif)
sd(rand_funfem_dopshif)

mean(rand_funhddc_dopshif)
sd(rand_funhddc_dopshif)
```





## Simulation Set - sinusoidal amount

```{r, include=FALSE}
true = c(rep(1,50),rep(2,50),rep(3,50),rep(4,50))

ccr <- function(result, true) {
  if(length(result) != length(true)) {warning('result vector and true vector has different size')}
  return(sum(true == result)/length(result))
}


ccr_kmeans_sinamount=vector()
rand_kmeans_sinamount=vector()

ccr_pam_sinamount=vector()
rand_pam_sinamount=vector()

ccr_funfem_sinamount=vector()
rand_funfem_sinamount=vector()

ccr_funhddc_sinamount=vector()
rand_funhddc_sinamount=vector()

for (k in 1:100) {
  set.seed(k)
  time = seq(0,1023/1024,length.out=1024)
  
  sinusoidal1 = matrix(0,nrow=1024,ncol=50)
  
  for (i in 1:1024) {
    sinusoidal1[i,]=abs(rnorm(50,sin(5*time[i]),0.5))
  }
  
  sinusoidal2 = matrix(0,nrow=1024,ncol=50)
  
  for (i in 1:1024) {
    sinusoidal2[i,]=1.1*abs(rnorm(50,sin(5*time[i]),0.5))
  }
  
  sinusoidal3 = matrix(0,nrow=1024,ncol=50)
  
  for (i in 1:1024) {
    sinusoidal3[i,]=1.2*abs(rnorm(50,sin(5*time[i]),0.5))
  }
  
  sinusoidal4 = matrix(0,nrow=1024,ncol=50)
  
  for (i in 1:1024) {
    sinusoidal4[i,]=1.3*abs(rnorm(50,sin(5*time[i]),0.5))
  }
  
  sinusoidal = cbind(sinusoidal1,sinusoidal2,sinusoidal3,sinusoidal4)
  
  sim_sinusoidal_amount <- convert_amount(sinusoidal)
  sim_sinusoidal_intensity <- convert_intensity(sinusoidal,8)
  sim_sinusoidal_pattern <- convert_pattern(sinusoidal,4)

  ###############################################MFPCA####################################################
  sim_sinusoidal_array = array(data=NA,dim=c(1024,ncol(sinusoidal),3))
  sim_sinusoidal_array[,,1]<-sim_sinusoidal_amount
  sim_sinusoidal_array[,,2]<-sim_sinusoidal_intensity
  sim_sinusoidal_array[,,3]<-sim_sinusoidal_pattern
  
  fdabasis = create.bspline.basis(rangeval=c(0,1024),norder=4,breaks = seq(0,1024,by=4))
  fdatime = seq(1, 1024, by=1)
  sim_sinusoidal_fdafd = smooth.basis(fdatime, sim_sinusoidal_array, fdabasis)$fd
  
  sinusoidalPca = pca.fd(sim_sinusoidal_fdafd,nharm=10)
  a<-vector()
  for(q in 1:10){
  	a[q]=sum(sinusoidalPca$varprop[1:q])
  	}
  q=which(a>0.9)[1]
  funPCscore<-sinusoidalPca$scores[,1:q,1]+sinusoidalPca$scores[,1:q ,2]+sinusoidalPca$scores[, 1:q,3]
  
  ##Kmeans
  num_cl=4
  MCluster <- kmeans(funPCscore, centers= num_cl, iter.max = 100000)
  cluster_result = best_match_factor(true,MCluster$cluster)
  
  ccr_kmeans_sinamount[k] <- ccr(true,cluster_result)
  rand_kmeans_sinamount[k] <- adjustedRandIndex(true,cluster_result)
  
  ##PAM
  num_cl=4
  MCluster <- pam(funPCscore, num_cl, metric="manhattan")
  cluster_result = best_match_factor(true,MCluster$cluster)
  
  ccr_pam_sinamount[k] <- ccr(true,cluster_result)
  rand_pam_sinamount[k] <- adjustedRandIndex(true,cluster_result)

  ## FunFEM
  fdabasis = create.bspline.basis(rangeval=c(0,1024),norder=4,nbasis=21)
  fdatime = seq(1, 1024, by=1)
  sim_sinusoidal_fdafd = smooth.basis(fdatime, sinusoidal, fdabasis)$fd
  res = funFEM(sim_sinusoidal_fdafd,K=4)

  cluster_result = best_match_factor(true,res$cls)
  
  ccr_funfem_sinamount[k] <- ccr(true,cluster_result)
  rand_funfem_sinamount[k] <- adjustedRandIndex(true,cluster_result)
  
  
  ##FunHDDC
  fdabasis = create.fourier.basis(rangeval=c(0,1024),period = 1024)
  
  fdatime = seq(1, 1024, by=1)
  sim_sinusoidal_fdafd = smooth.basis(fdatime, sinusoidal, fdabasis)$fd
  
  res <- funHDDC(sim_sinusoidal_fdafd,K=4)
  cluster_result = best_match_factor(true,res$class)
  
  ccr_funhddc_sinamount[k] <- ccr(true,cluster_result)
  rand_funhddc_sinamount[k] <- adjustedRandIndex(true,cluster_result)
  
}

```

```{r}
##CCR
mean(ccr_kmeans_sinamount)
sd(ccr_kmeans_sinamount)

mean(ccr_pam_sinamount)
sd(ccr_pam_sinamount)

mean(ccr_funfem_sinamount)
sd(ccr_funfem_sinamount)

mean(ccr_funhddc_sinamount)
sd(ccr_funhddc_sinamount)

##AdjustedRandindex
mean(rand_kmeans_sinamount)
sd(rand_kmeans_sinamount)

mean(rand_pam_sinamount)
sd(rand_pam_sinamount)

mean(rand_funfem_sinamount)
sd(rand_funfem_sinamount)

mean(rand_funhddc_sinamount)
sd(rand_funhddc_sinamount)
```
